### ISSUE TITLE
build: Upgrade the minimum CMake version to 3.26+

### ISSUE THREAD

**Issue by shirly121** [alibaba/neug#865]
## Problem

NeuG currently builds in CI with CMake 3.22.1. The new ZVec dependency used by the `vector_search` extension requires CMake 3.26 or newer, causing extension builds to fail during ZVec configuration.

The root error is:

```text
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.26 or higher is required.
  You are running version 3.22.1
```

The failing target is:

```text
extension/vector_search/zvec_external
```

The subsequent `gmake Error 2`, Python `CalledProcessError`, and process exit code 2 are consequences of this configuration failure rather than C++ compilation errors.

Failing GitHub Actions job: https://github.com/alibaba/neug/actions/runs/31478028400/job/93736240067?pr=851

## Proposed solution

Upgrade NeuG’s required and CI-provided CMake version to 3.26 or newer. This should include:

- Updating the documented/minimum supported CMake version for NeuG.
- Updating CI images or workflow setup to install and select CMake 3.26+.
- Updating development and packaging environments that still provide CMake 3.22.1.
- Verifying core, Python binding, extension, and package builds with the new baseline.

Using CMake 3.26+ is preferable to lowering ZVec’s declared minimum version without proving that ZVec supports older CMake releases.

## Acceptance criteria

- NeuG CI uses CMake 3.26 or newer.
- `extension/vector_search/zvec_external` configures without a CMake version error.
- Extension and package build jobs complete using the new CMake baseline.
- Build documentation reflects the updated requirement.
