### PR TITLE
fix: use aggregate initialization for search results

### PR DESCRIPTION
**Pull request by shirly121**
## Summary

Fix a macOS libc++ compilation error introduced by #742. `SearchResult` is an aggregate without a matching two-argument constructor, so constructing it through `vector::emplace_back(vid, score)` fails on the affected toolchain. Use explicit aggregate initialization before insertion instead.

Fixes the issue introduced by https://github.com/alibaba/neug/pull/742.

## Testing

- `ap_index_test`
- `tp_index_test`

### CODE REVIEW

**Review by zhanglei1949 — APPROVED** [review]
LGTM
